### ISSUE TITLE
Add index and metadata blog

### ISSUE THREAD

**Issue by ericof** [collective/collective.blog#27]
## Tasks

- [ ] Catalog: Add `blog` index
- [ ] Catalog: Add `blog` metadata
- [ ] Indexer: IAuthor should return the UID of a parent that has the `collective.blog.behaviors.blog.IBlogInfo` applied to it
- [ ] Indexer: IPost should return the UID of a parent that has the `collective.blog.behaviors.blog.IBlogInfo` applied to it
- [ ] Implement tests to validate indexers are working
