### ISSUE TITLE
Create folder authors inside a blog

### ISSUE THREAD

**Issue by ericof** [collective/collective.blog#32]
## Goals
- [x] When a new Blog is added, create a new Document with id `authors` and title `Authors` inside of it
- [x] Only allow Author content type to be added inside the `authors` container
- [ ] Add tests to make sure an Author could not be added outside the created container

## Tasks
- [x] Modify `rolemap.xml` and remove all roles from `collective.blog: Add Author`
- [x] Modify `Author.xml` and set global_allow to true
- [x] Modify `Blog.xml` and remove `Author` from the content-types that can be added
- [x] Create subscriber to listen to  Blog creation
- [x] Subscriber should create a new Document with id `authors` and title `Authors`
- [x] Subscriber should set, on `authors` the same roles used in `collective.blog: Add Blog` (rolemap.xml) to the `collective.blog: Add Author` permission
